pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/user/repo.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                python3 -m py_compile app.py
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                . venv/bin/activate
                pytest > test-results.log || true
                '''
            }
        }

        stage('LangChain Agent Analysis') {
            steps {
                sh '''
                . venv/bin/activate
                python3 ai_agent.py
                '''
            }
        }

        stage('Decision Gate') {
            steps {
                script {

                    def decision =
                        readFile('decision.txt').trim()

                    echo "Decision: ${decision}"

                    if (decision == "STOP") {
                        error(
                          "LangChain blocked deploy"
                        )
                    }

                    if (decision == "RETRY") {
                        retry(1) {
                            sh '''
                            . venv/bin/activate
                            pytest
                            '''
                        }
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                sh './deploy.sh'
            }
        }
    }
}
