pipeline {

    agent any

    environment {
        OPENAI_API_KEY = credentials('OPENAI_API_KEY')
    }

    stages {

      
        stage('Install Dependencies') {
            steps {
                sh '''
                cd agentic-cicd
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                cd agentic-cicd
                venv/bin/python -m py_compile app.py
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                cd agentic-cicd
                venv/bin/pytest > test-results.log || true
                '''
            }
        }

        stage('LangChain Agent Analysis') {
            steps {
                sh '''
                cd agentic-cicd
                venv/bin/python ai_agent.py
                '''
            }
        }

        stage('Decision Gate') {
            steps {
                script {

                    def decision =
                        readFile('decision.txt').trim()

                    echo "Decision: ${decision}"

                    if (decision == "STOP") {
                        error(
                          "LangChain blocked deploy"
                        )
                    }

                    if (decision == "RETRY") {
                        retry(1) {
                            sh '''
                            cd agentic-cicd
                            venv/bin/pytest
                            '''
                        }
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                sh './deploy.sh'
            }
        }
    }
}
